Google authentication, session management, initial routing - AB#42
fiit-tp7-2023/frontend pull request #2
Opened 2023-10-16 17:31 UTC by Kesuera

2023-10-16 18:28 UTC, brano-hozza requested changes
Please add `.env.example` file, so we know which variables should be provided

2023-10-16 18:28 UTC, brano-hozza commented on pages/index.vue
> +    <button @click="goToPage('/project/login')">Project section</button>
Router instance is auto-injected in nuxt, you can use `$router.push(...)` instead of custom function

2023-10-16 18:28 UTC, brano-hozza commented on layouts/team.vue
I don't think this layout is necessary, we can use default layout for team instead

2023-10-16 18:28 UTC, brano-hozza commented on pages/index.vue
> +  auth: false,
I would move this meta to default layout

2023-10-16 18:28 UTC, brano-hozza commented on pages/team/about.vue
> +  layout: "team",
As mentioned earlier

2023-10-18 18:53 UTC, Kesuera commented
I added a .env.example file, changed routing to use $router.push(...) and made some layout changes => default layout is for project, team layout is preserved and default index page is the team dashboard page from which user can move to project section.

2023-10-18 19:19 UTC, brano-hozza approved these changes, later dismissed

2023-10-18 19:48 UTC, steboee approved these changes

2023-10-18 19:56 UTC, merged