AB#109 Shorter eth address component
fiit-tp7-2023/frontend pull request #22
Opened 2023-11-10 22:24 UTC by Kesuera

Swapped basic html title with naive ui tooltip and transformed the actual component into a naive ui button that looks like text, but gets highlighted on click

2023-11-11 08:27 UTC, kikz0rsk approved these changes

2023-11-11 09:22 UTC, brano-hozza requested changes

2023-11-11 09:22 UTC, brano-hozza commented on components/project/other/TruncatedAddressComponent.vue
> +  (document.activeElement as HTMLElement | null)?.blur();
I believe that `@click` can provide event information and from the event you can get target (active element). Using that over document.activeElement could be better approach.

2023-11-12 11:26 UTC, brano-hozza approved these changes

2023-11-12 11:26 UTC, merged