AB#166 Endpoint for processing md2pdf
fiit-tp7-2023/frontend pull request #39
Opened 2023-11-16 19:59 UTC by Kesuera

2023-11-16 20:07 UTC, brano-hozza requested changes

2023-11-16 20:07 UTC, brano-hozza commented on constants/regex.ts
> +export const SAFE_CONTENT_RELATIVE_PATH_REGEX = /^[a-zA-Z0-9_-]+\/[a-zA-Z0-9_-]+\.md$/;
I believe this will include only first directory level. This should accept any amount of levels and exclude ".." path

2023-11-17 11:42 UTC, Kesuera commented
I've tried multiple fix attempts to resolve the problem with puppeteer. None of them were successful.. The problem is probably related to vercel. I would merge this code, so the endpoint is ready and when we have our own server. We can further examine if the problem still exists. Previous requested changes were incorporated.

2023-11-17 12:38 UTC, brano-hozza approved these changes

2023-11-17 12:38 UTC, merged