AB#179 Add link to Etherscan
fiit-tp7-2023/frontend pull request #69
Opened 2023-12-08 18:57 UTC by ktothova

- added link to etherscan 
- added useHead
- changed favicon.ico to our logo

2023-12-08 19:21 UTC, brano-hozza requested changes

2023-12-08 19:21 UTC, brano-hozza commented on pages/project/login.vue
> +  title: 'Project page - Login',
Graph explorer - Login

2023-12-08 19:21 UTC, brano-hozza commented on components/project/sections/NftInfo.vue
> +useHead({
Graph explorer - NFT

2023-12-08 19:21 UTC, brano-hozza commented on components/project/sections/NftInfo.vue
> +              <svg
Couldnt we use some icon from library?

2023-12-08 19:25 UTC, ktothova commented on components/project/sections/NftInfo.vue
> +              <svg
didn't work sadly

2023-12-08 20:21 UTC, brano-hozza requested changes

2023-12-08 20:21 UTC, bran0h commented on components/project/sections/NftInfo.vue
> +import { NSkeleton, NDataTable, NButton } from 'naive-ui';
Please remove naive component imports, they are auto-imported. Keep just type import

2023-12-08 20:21 UTC, brano-hozza commented on .vscode/settings.json
> +  "editor.codeActionsOnSave": ,
Please update from main branch

2023-12-09 08:08 UTC, brano-hozza approved these changes

2023-12-09 08:08 UTC, merged